export const ADD_WORD_TO_SEARCH = "ADD_WORD_TO_SEARCH";
export const DELETE_WORD_FROM_SEARCH = "DELETE_WORD_FROM_SEARCH";
export const SEARCH_WORDS_BEGIN = "SEARCH_WORDS_BEGIN";
export const SEARCH_WORDS_SUCCESS = "SEARCH_WORDS_SUCCESS";
export const SEARCH_WORDS_FALIURE = "SEARCH_WORDS_FALIURE";
export const TOGGLE_WORD_VISIBILITY = "TOGGLE_WORD_VISIBILITY";
export const EDIT_SEARCHED_WORDS = "EDIT_SEARCHED_WORDS";